version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: airflow-postgres
    networks:
      - weather_net
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-airflow}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-airflow}
      POSTGRES_DB: ${POSTGRES_DB:-airflow}
    volumes:
      - postgres_data:/var/lib/postgresql/data  # استفاده از Named Volume برای پایداری بیشتر
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      retries: 5

  airflow-init:
    build: .
    container_name: airflow-init
    networks:
      - weather_net
    depends_on:
      postgres:
        condition: service_healthy
    environment: &airflow-common-env
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER:-airflow}:${POSTGRES_PASSWORD:-airflow}@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY:-FB09z_S7W5u6M9E9b5r7X_8l6N5c4V3B2A1a_=}
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__TEST_CONNECTION: 'Enabled'
      # اضافه کردن متغیر زیر برای دسترسی صحیح به فایل‌ها در محیط لینوکس
      AIRFLOW_UID: ${AIRFLOW_UID:-1000} 
    command: >
      bash -c "airflow db upgrade && 
      airflow users create --username admin --password admin --firstname Airflow --lastname Admin --role Admin --email admin@example.com || true"

  airflow-webserver:
    build: .
    container_name: airflow-webserver
    networks:
      - weather_net
    ports:
      - "8085:8080"
    environment: *airflow-common-env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
      - ./sql:/opt/airflow/sql  
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    command: webserver
    restart: always

  airflow-scheduler:
    build: .
    container_name: airflow-scheduler
    networks:
      - weather_net
    environment: *airflow-common-env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
      - ./sql:/opt/airflow/sql  
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    command: scheduler
    restart: always

volumes:
  postgres_data: # تعریف Volume برای دیتابیس داخلی ایرفلو

networks:
  weather_net:
    external:
      name: shared_weather_net